### ISSUE TITLE
Crash when subtitle is missing in plist

### ISSUE THREAD

**Issue by steipete** [bitstadium/HockeyKit#1]
When subtitle is missing, the attempt to save the dictionary in user preferences fails (due to the nil) and the app crashes when trying to open the update page.

**Comment by DerAndereAndi** [comment]
Will be fixed together with a bug where it crashes when no beta version is available on the server

**Comment by DerAndereAndi** [comment]
I just uploaded a patch which also contains a fix for this

**Comment by steipete** [comment]
awesome, thanks!
