### ISSUE TITLE
Download of .ipa file fails because of wrong/lost port number

### ISSUE THREAD

**Issue by tvb117** [bitstadium/HockeyKit#100]
Hello Hockeykit Team,

I think there is a bug if you use a non default port. 

The url of my server looks like this: https://mydomain.com:8020/

The hockeykit is running and I can access it, but the download will fail with the error message "Can not connect to mydomain.com".  

If I click on "install", the App requests the following:

https://mydomain.com:8020/api/2/apps/bundleidentifier?format=plist

and receives a plist where the url is incorrect:

<key>url</key>
<string><![CDATA[https://mydomain.com/bundleidentifier/myapp.ipa]]></string>

The port 8020 is missing now, thus the download fails.

Unfortunately I can not use the default port for https. Could you tell me how I can fix this ?

**Comment by DerAndereAndi** [comment]
Hi,

the code looks fine, but I cannot test it right now. The relevant file is `router.php` and the code in question is

```
    $protocol = 'http';
    $default_port = 80;
    if (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on')
    {
        $protocol = 'https';
        $default_port = 443;
    }
    $this->baseURL = sprintf(
        '%s://%s%s%s/',
        $protocol,
        $_SERVER['SERVER_NAME'],
        $_SERVER['SERVER_PORT'] != $default_port ? ':'.$_SERVER['SERVER_PORT'] : '',
        $path
```

You might want to add some logging in there to see what happens on your server.
- Andreas

**Comment by tvb117** [comment]
Hi,

thanks for your quick reply. The code is correct. It was a server problem.

**Comment by casibbald** [comment]
Can anyone specify what the server problem was as I am experiencing this same problem.
