### ISSUE TITLE
Authentication procedure for Android 

### ISSUE THREAD

**Issue by phimi** [bitstadium/HockeyKit#101]
Please add a mechanism to authenticate android users, so that not everyone can download apks
The most android browser don't support downloading of apks behind basic http auth

**Comment by DerAndereAndi** [comment]
There is no reliable device ID available on android devices which could be work. The other alternative would be to add user management and incorporate authentication into the framework. This is currently not in our focus.

An alternative would be to use our hosted service HockeyApp, where you can restrict the download to registered users only. This won't help if those would share the .apk though behind your back.
