### ISSUE TITLE
Hockey iOS Portal Device Parser fails

### ISSUE THREAD

**Issue by vinzenzweber** [bitstadium/HockeyKit#112]
The "Hockey iOS Portal Device Parser" fails importing Devices with the message

> elIDs is null

**Comment by DerAndereAndi** [comment]
Working fine over here. Can't reproduce.

**Comment by vinzenzweber** [comment]
just checked again with Safari and it works while Firefox fails ...
any ideas? maybe some addons?

**Comment by DerAndereAndi** [comment]
Yep, seems Firefox is incompatible with the RegEx call in the code.

```
var expIDs = /<td class="id" title="([^"]+)/g;
var elIDs= document.body.innerHTML.match(expIDs);
```

This does not work. Maybe someone knows a fix.
