### ISSUE TITLE
Problems with subdomain

### ISSUE THREAD

**Issue by Mondgewitter** [bitstadium/HockeyKit#114]
Hello, I'm having Problems with Hockey since I wanted to use a subdomain for the hockey update url.

Before I used a url like that: http://www.mydomain.com/public/ and everything worked fine.
Now I made a subdomain like http://subdomain.mydomain.com which redirects to the url above. When starting the app, hockey doesn't inform me about a new version (but I know there is one).

Then I added the BWHockeyViewController to my app. Now I can press "check" and hockey tells me "Server returned empty response".

Edit: I still can visit the website through iPhone and install the app from the site.

Any ideas what is going wrong here?

**Comment by DerAndereAndi** [comment]
Hi,

turn on logging on the client `setLogging: YES` to see where the requests go and what responses you get. Compare that with your server logs. Then you hopefully will be able to find the cause of the problem.

**Comment by Mondgewitter** [comment]
Ok, thanks for the setLogging hint, didnt know about that. 
The log output in the client tells me it is sending the request to http://subdomain.mydomain.com/api/2/apps/...and so on. That sounds correct to me since the subdomain is redirecting directly to the public directory. But then it receives the following response:

<html><head>
<title>302 Found</title>
[...]
<p>The document has moved [...]

From the stuff I've read in the issues here so far, I think I need to change the rewrite rules in the .htaccess file. But I'm totally unexperienced with that. 

Edit: If I open the url the logger gives me in a normal browser I get a json with the name of my app, the version and so on.

**Comment by DerAndereAndi** [comment]
Basically you would need the content of the original .htaccess to be in the /public/ folders .htaccess file. See: https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/public/.htaccess

**Comment by Mondgewitter** [comment]
Yes thats the case at the moment of course. But I thought that I may need to modify it because of the redirect?!

**Comment by DerAndereAndi** [comment]
I have no idea how you setup a redirect or your subdomain. Usually you could point the subdomain to have the public folder as root.

**Comment by Mondgewitter** [comment]
Yes thats, what I did. In the control panel  of my hoster I simply enter the subdomains name and let it point to http://www.mydomain.com/public/

**Comment by DerAndereAndi** [comment]
Sorry, no idea. Also without direct access it is hard to really know what you did and what is going on.
Also you are always saying it is "redirecting", which is very confusing since you now say that subdomain points directly to that folder so there should not be any redirecting. Still you get 302 error which says the URL is redirected and wants the client to use the new URL. But the client does not follow such redirects. So your setup sounds really weird. Try not to use redirects.

**Comment by Mondgewitter** [comment]
Hm ok sorry, well if I let the sub domain point to a url like I mentioned it is a redirect I think. Im not using a relative path for the subdomain. So as I understand, redirects are not working.
Thanks, for your help so far.
