### ISSUE TITLE
app.html doesn't show up for Android

### ISSUE THREAD

**Issue by mobinauten** [bitstadium/HockeyKit#115]
Although placed in the Android folder the html isn't show. Everything else works, and also the app.html works for iOS properly. 
Thx
Olli

**Comment by ashtom** [comment]
The .html file is not used for Android, but instead the notes are read from the .json file, see this commit:
https://github.com/TheRealKerni/HockeyKit/commit/d65c5a0d8379197dec11757209432e0e7fc0ebc2

Something like this should work:

<pre>{
  "title": "HockeyDemo",
  "versionCode": 2,
  "versionName": "1.0"
  "notes": "Insert your release notes here."
} </pre>


If you still want to use the .html file, just remove line 577 from main.php:
https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/includes/main.php#L577

**Comment by mobinauten** [comment]
Works like a charm, thanks!
