### ISSUE TITLE
HockeyKit working on iPhone but not on iPad

### ISSUE THREAD

**Issue by bsrz** [bitstadium/HockeyKit#116]
I was wondering if there are anyone aware of an issue where HockeyKit works on iPhone but not on iPad.
I know this because our app will use Quincy perfectly in both.  Same piece of code.  iPhone will trigger the update (ignore, update) but nothing happens on iPad.

**Comment by DerAndereAndi** [comment]
Hi, we haven't heard of such an issue. Have you tried to debug it or to turn logging on and check the output?

**Comment by bsrz** [comment]
Ok, I've done a few more tests...
Seems to be happening only on first gen iPads.  iPad2s work fine.
This is getting weirder.  I'm having issues with certificates right now, so I can't debug/log information on the device yet.  I will test in debug mode a bit later.

**Comment by bsrz** [comment]
I have reconfirmed this.
I restored the iPad1.  Installed a version of our app, and never got the pop up to upgrade.  I am able to send crash reports though.
I did the same with iPad2.  Installed same version (same .ipa) of our app, and got the popup asking to upgrade.

If you can think of anything causing this, please let me know, I'm a bit out of leads here....

**Comment by DerAndereAndi** [comment]
The only reason I could think of is that the UDID of the iPad 1 is either missing in the new provisioning profile or that you restricted access to the new version and the iPad 1 does not have access.

There is no technical reason from the SDK itself why it should not work.
