### ISSUE TITLE
App-dl working on Browser and Droid, not on iPhone

### ISSUE THREAD

**Issue by chrsch** [bitstadium/HockeyKit#118]
Hi,

I have two apps stored in separate dirs (com.domain.app1iOS, com.domain.app1Android). Each Dir has subdirs for versions (alpha00, alpha01,...).  Each sub dir contains for ios: .ipa, .plis, .html and for Android: .apk, .json, .html

Using a browser the download of the ipa and apk files works.

Using a browser on an Android device works as well, the apk installs fine.

Using safari on iOS5 doen't for however, nothing happens at all.

I tried to figure out whats going on, the generated download url on iOS looks like this: 

itms-services://?action=download-manifest&url=http://subdomain.domain.com/api/2/apps/com.domain.app1iOS?format=plist

Any ideas whats going on or hints what to try?

Maybe there is still something broken using ios5?

Regards,
Christoph

**Comment by DerAndereAndi** [comment]
Hi,

try to download the plist file in that URL and check if the URL to the .ipa file is replaced correctly. Remember to put "**URL**" into the plist files for each iOS app version you upload!
- Andreas

**Comment by chrsch** [comment]
Hi,

I have placed _ _ URL_ _  in the manifest file. The url doen't point to the .ipa file but to the drectory the directories for the version reside in. What shoul the '&url=...." part look like at all?

Thanks!
Christoph

**Comment by DerAndereAndi** [comment]
The URL above should download the plist. If this doesn't work, you most likely have a problem with your redirect rules setup.

If the download of the plist succeeds, its content should have a pointer directly to the IPA.

**Comment by chrsch** [comment]
This is what the generated url looks like.. It's not linking to an .plist at all... or is this, what the rewrite is supposed to do?

itms-services://?action=download-manifest&url=http://hockey.foodomain.com/api/2/apps/com.foodomain.appiosalpha?format=plist

**Comment by DerAndereAndi** [comment]
Enter http://hockey.foodomain.com/api/2/apps/com.foodomain.appiosalpha?format=plist into your browser and check if it works.

**Comment by chrsch** [comment]
Okay, the .plist looks good. url to ipa is correct.

One problem might be the bundle-identifier, must the app dir be named accordingly?

```
<plist version="1.0">
<dict>
<!-- array of downloads. -->
<key>items</key>
<array>
<dict>
<!-- an array of assets to download -->
<key>items</key>
<array>
<!-- software-package: the ipa to install. -->
<dict>
<!-- required. the asset kind. -->
<key>kind</key>
<string>software-package</string>
<!-- required. die URL der zu ladenden Datei. -->
<key>url</key>
<string>
<![CDATA[
http://hockey.foodomain.com/com.foodomains.appiosalpha/Alpha00/app.ipa
]]>
</string>
</dict>
<dict>
<key>kind</key>
<string>display-image</string>
<key>needs-shine</key>
<false/>
<key>url</key>
<string>
http://hockey.foodomain.com/com.foodomains.appiosalpha/app.png
</string>
</dict>
</array>
<key>metadata</key>
<dict>
<!-- required. -->
<key>bundle-identifier</key>
<string>com.foo-domains.appiosalpha</string>
<!-- optional (software only) -->
<key>bundle-version</key>
<string>0.0.00</string>
<!-- required. the download kind. -->
<key>kind</key>
<string>software</string>
<!--
optional. displayed during download; typically company name
-->
<key>kind</key>
<string>display-image</string>
<!--
required. the title to display during the download.
-->
<key>title</key>
<string>App (iOS)</string>
</dict>
</dict>
</array>
</dict>
</plist>
```

**Comment by DerAndereAndi** [comment]
Yes, check this wiki page https://github.com/TheRealKerni/HockeyKit/wiki/Server which says under 2.

> Create a new subdirectory with the name of the bundle identifier of your application, e.g. com.yourcompanyname.myapplicationbeta, later referred as the application directory

**Comment by chrsch** [comment]
Hm, fixed the dir name and file names to match the identifier. Still not working. The generated plist now looks like this (just replaces realAppName with app and real-domain.com with foo-domain.com).

Any further directions? Thanks for this lightning fast answers!

```
<plist version="1.0">
<dict>
<!-- array of downloads. -->
<key>items</key>
<array>
<dict>
<!-- an array of assets to download -->
<key>items</key>
<array>
<!-- software-package: the ipa to install. -->
<dict>
<!-- required. the asset kind. -->
<key>kind</key>
<string>software-package</string>
<!-- required. die URL der zu ladenden Datei. -->
<key>url</key>
<string>
<![CDATA[
http://hockey.foo-domain.com/com.foo-domain.app/app00/app.ipa
]]>
</string>
</dict>
<dict>
<key>kind</key>
<string>display-image</string>
<key>needs-shine</key>
<false/>
<key>url</key>
<string>
http://hockey.foo-domain.com/com.foo-domain.app/app.png
</string>
</dict>
</array>
<key>metadata</key>
<dict>
<!-- required. -->
<key>bundle-identifier</key>
<string>com.foo-domain.app</string>
<!-- optional (software only) -->
<key>bundle-version</key>
<string>0.0.00</string>
<!-- required. the download kind. -->
<key>kind</key>
<string>software</string>
<!--
optional. displayed during download; typically company name
-->
<key>kind</key>
<string>display-image</string>
<!--
required. the title to display during the download.
-->
<key>title</key>
<string>App (iOS)</string>
</dict>
</dict>
</array>
</dict>
</plist>
```

**Comment by DerAndereAndi** [comment]
Is this pointing to the correct .ipa file ? http://hockey.foo-domain.com/com.foo-domain.app/app00/app.ipa

Otherwise, it all is a setup issue. I can only guess what you are doing or not on your server. By theory the documentation should have discovered all steps. As a side note, you might want to check out http://hockeyapp.net/ a service providing this functionality and far more, also developed by myself and my colleagues.

**Comment by chrsch** [comment]
Finally figured out the .plis template I used was malformed in some way. Grabed a new one from https://developer.apple.com/library/ios/#featuredarticles/FA_Wireless_Enterprise_App_Distribution/Introduction/Introduction.html and now everything works. Thanks for your support! And yes, hockeyapp is on my roadmap later on ;-)
