### ISSUE TITLE
Extract UDIDs

### ISSUE THREAD

**Issue by holtwick** [bitstadium/HockeyKit#12]
Hi, I wrote a little Python script that helps extracting the UDIDs and names of the registered devices. You might want to add this or something similar to Hockey. Cheers Dirk

```
data = """

    PASTE HTML SOURCE CODE OF THE FOLLOWING PAGE HERE
    https://developer.apple.com/ios/manage/devices/index.action

"""

import re

udids = re.findall("<td class=\"id\">([^<]+)</td>", data)
names = re.findall("<td class=\"name\">.*?<span>([^<]+)", data)

for i in range(len(udids)):
    print "%s;%s" % (udids[i], names[i])
```

**Comment by DerAndereAndi** [comment]
I guess writing a bookmarklet is best for that, and creating an output that could be put into the userlist.txt file 1:1. Will look into it, thanks for the suggestion Dirk!

**Comment by holtwick** [comment]
You're right, a bookmarklet is even better. Great idea!

**Comment by DerAndereAndi** [comment]
Well, I enhanced the regex to be a little more fail safe and added the bookmarklet to the wiki, sadly I wasn't able to embed the bookmark link just to drag out due to GitHub limitations (Or I did not find out how to do it properly).

So here you go: https://github.com/TheRealKerni/Hockey/wiki/PHP-Server

**Comment by holtwick** [comment]
You can but arbitrary HTML into Markdown, like this:

```
<div>
  <a href='javascript:(function(){var expIDs = /<td class="id" title="([^"]+)/g;var elIDs= document.body.innerHTML.match(expIDs);var expNames=/<td class="name">.*?<span([^<]+)/g;var elNames=document.body.innerHTML.match(expNames);var content = "";for (var i=0; i<elIDs.length; i++){var id=elIDs[i].substr(elIDs[i].lastIndexOf("79ba73aa62ee2bcf89cf1f88266ea89008565ef5quot;")+1);var name="";if (elNames[i].search("<span title=")>-1){var start=elNames[i].lastIndexOf("title=")+7;var amount=elNames[i].lastIndexOf(">")-1-start;name=elNames[i].substr(start,amount);}else{name=elNames[i].substr(elNames[i].lastIndexOf(">")+1);}content+=id+";"+name+"\n";}document.body.innerHTML=content;alert("Copy the content and paste it into userlist.txt in your Hockey stats directory")}());'>Bookmarklet</a>
</div>
```

I tested it with this one: http://attacklab.net/showdown/ 

But you should also add it to the Stats page itself, so people know about the feature.

**Comment by DerAndereAndi** [comment]
The problem is that github removes javascript code from the link, so it is an empty link that you cannot use. Repo update is next.
