### ISSUE TITLE
iOS package version

### ISSUE THREAD

**Issue by bryanrahn** [bitstadium/HockeyKit#120]
I can't find anywhere to tell what version I have based on the iOS package. Can you include the version number within the iOS package?

**Comment by DerAndereAndi** [comment]
Same answer as here: https://github.com/TheRealKerni/QuincyKit/issues/86 :) Yes, will add it in the next version. Thanks.

**Comment by jacobweber** [comment]
It looks like that solution only works if you're using the HockeyKit iOS client. Will there be a way to specify the version if you're only using the HockeyKit server (like you can with Android)?
