### ISSUE TITLE
Undefined Indexes

### ISSUE THREAD

**Issue by jriker1** [bitstadium/HockeyKit#122]
When I execute index.php it works however the iPad, not the regular desktop version, has two index warnings.

FIRST ONE RIGHT AFTER THE WORD Version: AND BEFORE THE ACTUAL VERSION NUMBER:
# 

A PHP Error was encountered

Severity: Notice

Message: Undefined index: subtitle

Filename: views/index.php

Line Number: 251
# 

SECOND ONE AFTER THE RELEASE DATE AND BEFORE THE INSTALL APPLICATION BUTTON:
# 

A PHP Error was encountered

Severity: Notice

Message: Undefined index: profile

Filename: views/index.php

Line Number: 265
# 

Note line numbers may be slightly off as I added a line or two in the file but these warnings existed before this.

**Comment by nyanev** [comment]
You should put the provision profile in the app directory and in the .plist file add this 

```
<key>subtitle</key>
<string>1.0</string>
```
