### ISSUE TITLE
URL for a specific version of an app?

### ISSUE THREAD

**Issue by jessbowers** [bitstadium/HockeyKit#124]
Is it possible to access a specific version of an app?  What is the URL scheme for this?  I tried the following thinking it would work:

```
http://www.example.com/apps/com.mydomain.myapp/version-2.0.2a42
```

But it gives a 404.

**Comment by DerAndereAndi** [comment]
Hi Jess,

no, this is not supported.

**Comment by jessbowers** [comment]
ok thanks. Are there common scenarios for putting specific versions of an app in different directories (alternate bundleID)?  The use case is that I'd like to "freeze" a particular version for distribution to a beta testing team while continuing to work on the less stable edge release.

**Comment by DerAndereAndi** [comment]
You can restrict versions to a set of UDIDs. Search for "Restricting access to specific teams (iOS only)" here: https://github.com/TheRealKerni/HockeyKit/wiki/Server

**Comment by jessbowers** [comment]
cool, thanks

**Comment by HHuckebein** [comment]
I was not able to make that work.
Anything else I've to consider when using .team file inside a version directory?

Inside the stats directory I've the userlist.txt file.
