### ISSUE TITLE
Warning on LLVM 4 with XCode 4.4

### ISSUE THREAD

**Issue by arodeus** [bitstadium/HockeyKit#132]
Hi,
JSONKit library give the following warnings:

... HockeyKit/JSON/JSONKit.m:2562:11: Direct access to objective-c's isa is deprecated in favor of object_setClass() and object_getClass()

**Comment by arodeus** [comment]
I'm testing the following solution, based on the compiler hint:

THIS:
 if(JK_EXPECT_T(object_getClass(object) == encodeState->fastClassLookup.stringClass))     { isClass = JKClassString;     }

INSTEAD OF THIS:
 if(JK_EXPECT_T(object->isa == encodeState->fastClassLookup.stringClass))     { isClass = JKClassString;     }

**Comment by BenMoment** [comment]
arodeus - any updates? Thanks...

**Comment by DerAndereAndi** [comment]
I just updated JSONKit to the latest version in the develop branch that is available in its repository over here: https://github.com/johnezang/JSONKit

**Comment by BenMoment** [comment]
Thanks!
