### ISSUE TITLE
?Format=plist Issues

### ISSUE THREAD

**Issue by ghost** [bitstadium/HockeyKit#137]
So my file plist is not mapping correctly. If I do "myip/api/2/apps/appname?format=ipa" the file downloads perfect. If I do the same thing but ?format=plist I get this error. 

This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

IE told me this :
XML5632: Only one root element is allowed.

Any Ideas?

**Comment by tfonfara** [comment]
Please check my answer in #182
