### ISSUE TITLE
The requested URL [...]/public/api/2/apps/  was not found on this server.

### ISSUE THREAD

**Issue by ghost** [bitstadium/HockeyKit#138]
I tried to install the HockeyKit local at my Mac.
After doing the default server setup: https://github.com/TheRealKerni/HockeyKit/wiki/Server
I have two problems:
- Downloading the file at every PC / Mac in network works fine but downloading with an iOS Device aborts: "Cannot connect to [...].local
- Downloading the Profile doesn't work at all. Because there is a linking error.
- The requested URL /hockeyKit/public/api/2/apps/[...].HockeyDemo was not found on this server.

Can someone show me his customized .htaccess-files?
Because as far as I can see it's rather a PHP and Apache2 problem than of the HockeyKit-component.

**Comment by ghost** [comment]
It was a problem of Apache2 and the rewrite_module. 
Just changed the AllowOverride to ALL at the right position and it works fine.

**Comment by joeg1ff** [comment]
Where did you change it to? in the sites-enabled folder?
