### ISSUE TITLE
All application versions display, release notes for Android?

### ISSUE THREAD

**Issue by czaku** [bitstadium/HockeyKit#142]
Hey

Is there any chance to have the view of all apps versions to display, or is there any chance to be able to download previous versions of the application somehow?

The other issue is that I have .html file for Android app with some content but it's not showing on the main page.

**Comment by saulpower** [comment]
I found that you can just add release notes in the .json manifest file with a tag of "notes":

```
{
    "title": "MoneyMobile",
    "versionCode": 1,
    "versionName": "1.0",
    "notes": "<!DOCTYPE html><html><body><h1>Release Notes</h1><p>This is a test of release notes</p></body></html>"
}
```

**Comment by FabianFrank** [comment]
Now you can also have relnotes.html for Android apps, see:
https://github.com/TheRealKerni/HockeyKit/commit/eb247e08e93e2cb7c1f64a74837d83f8ddc21b15
