### ISSUE TITLE
Failed Enable "Stats"-feature

### ISSUE THREAD

**Issue by truongvinht** [bitstadium/HockeyKit#158]
Hi,

first: thanks for the great framework. I like the concept of HockeyKit very much.

Problem:
I failed to record information for the "stats/index.php" page.

I tried following (using instructions: https://github.com/TheRealKerni/HockeyKit/wiki/Server )
1. reimplement customDeviceIdentifier method
2. set delegate and [[BWHockeyManager sharedHockeyManager] setSendUserData:YES];
3. on the server I configured in the stats folder: userlist.txt
UDID;the testers name

Did I do anthing wrong or did I miss anything? The server never gets any records about devices.

**Comment by DerAndereAndi** [comment]
What does `reimplement customDeviceIdentifier` method mean? You can safely use the iOS provided method to get the UDID of the device. Just make sure not to ship it into your appstore builds and tell the compiler to ignore deprecated warnings.

On the server make sure that the file is writable for the web server.

**Comment by FabianFrank** [comment]
Did you check the apache error log to see what happens when a device pings the server for an update check? There are really multiple reasons why writing the stats can fail, for example permissions on disk, etc.

**Comment by truongvinht** [comment]
thanks for the quick reply. I checked the apache logs and figure out that there is an access problem

PHP Warning:  mkdir(): Permission denied in MY-PATH/includes/logger.php on line 28

The Folder should be read- and writeable. 

I already tried this: http://stackoverflow.com/questions/5246114/php-mkdir-permission-denied-problem

But still can't help me so much. any other idea? Thanks in advance !

**Comment by FabianFrank** [comment]
Did the permission problem go away or is it still logged? If so, you can try to set the permissions on the stats directory like this:
$ chmod -r 777 stats
To see if it fixes the issue, or if something further comes up. Please always post your error log if so. Thank you!

**Comment by grangej** [comment]
I also have this problem on Mavericks, even with 777, this is making no sense to me.

**Comment by FabianFrank** [comment]
Does the path maybe exist as a file?

**Comment by grangej** [comment]
No, does this have anything to do with the path being in my user directory?

The path is /Users/username/sites/sitename/stats

Here is the directory : 

drwxrwxrwx   8 _www         staff    272 Mar  7 18:44 stats
