### ISSUE TITLE
Add support in server for download link to only latest file

### ISSUE THREAD

**Issue by dhiraj** [bitstadium/HockeyKit#16]
The server code picks up the _first_ file it finds with .plist and .ipa. Please consider changing the code main.php in includes folder to iterate through all available files and pick up only the latest one.

This would make it a much easier task to upload a fresh build - fire and forget with a batch file would be really easy. Currently I am solving this problem by deleting all files in the app's folder on the server using rsync, in my batch file, but it feels... hackish in an otherwise excellent mechanism. :)

Really great work making this framework, I am not really using the framework on the client side, but just the server code - didn't particularly care to have auto-update in the client (and risk forgetting to add an #ifdef somewhere). 

Please keep up the good work,
Regards,
Dhiraj.

P.S. In case other people would like to use my rsync workaround, here's my 1 line rsync command, simply dump into an .sh file, give it execute permission, and you're set. :)
Of course, the command is to be used at your own risk, please be careful what you put in the TARGET_PATH, rsync will delete _everything_ in that folder.

rsync -z -i -u -vv -h -r --progress --delete /FULL_SOURCEFOLDER_PATH/ USER@SERVER:/TARGET_PATH/

**Comment by DerAndereAndi** [comment]
Hello, I don't see the benefit. Since the only reason you need that, is you manually renamed the ipa file containing e.g. the version number. And then uploading it via rsync. Why would you need to old version on the server anyway? Why not using SCP to upload the new .ipa file to the server as done in the example build script.

Andy

**Comment by dhiraj** [comment]
Hmm... yes, I do see your point. I guess my scenario is a bit weird - it would make perhaps more sense to include a line in the README that states something like this? 

"Don't make separate names per ipa you make, else the first one will be served".

**Comment by DerAndereAndi** [comment]
Good point. I will.
