### ISSUE TITLE
How to support iOS 7.1?

### ISSUE THREAD

**Issue by yunzixun** [bitstadium/HockeyKit#169]
I changed http to https, and add ssl support in Apache server , like url below:
itms-services:///?action=download-manifest&url=https://www.xxx.com/api/2/apps/com.xxx.xxx/app.plist?format=plist

After I open hokeykit site in ipad safari, and click the install Application button, the device prompt error "cannot connect to www.xxx.com", it seems the rewrite rule does not work such that safari could not find the real ipa file path?

**Comment by DerAndereAndi** [comment]
The redirect rules are not protocol specific, check yourself: https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/public/.htaccess

The following ticket might provide some hints on what may be wrong with your server setup: https://github.com/TheRealKerni/HockeyKit/issues/168

**Comment by truongvinht** [comment]
So is it impossible to support iOS 7.1 without having any SSL certificate? I tried with self signed SSL certificate and still get the message " cannot connect to ...". Apple really closed the doors, but it seems too many doors

**Comment by FabianFrank** [comment]
Yes, you need a certificate. Please reopen if it doesn't work with a valid SSL cert.
