### ISSUE TITLE
"Install Application" do not work @iOS 7.1

### ISSUE THREAD

**Issue by omid1234** [bitstadium/HockeyKit#170]
After we configure the Apache and the PHP Service we was able to deliver a page with our App inside. It is possible to download the App from the Mac. We care about the Requirement from iOS 7.1 that only SSL will work , for that Reason we use that "https" URL. 

URL@Mac:
https://apps.bis.epost-dev.de/app/clients/epost/bundles/de.epost.epostapp/45432563v1/ePost_App.ipa

URL@iPhoneWith_iOS7.1(URL_Encrypted):
itms-services://?action=download-manifest&amp;url=https%3A%2F%2Fapps.bis.epost-dev.de%2Fapp%2Fclients%2Fepost%2Fapi%2F2%2Fapps%2Fde.epost.epostapp%3Fformat%3Dplist%26version%3D45432563v1

Maybe you could give us more informations about the configuration process. .htaccess File , Rewrite-Rules...etc.

Thanks a lot :+1: 

Omid

**Comment by DerAndereAndi** [comment]
The redirect rules are defined here: https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/public/.htaccess

I can't help you with the specific issues on your own server setup. Your links look pretty fine to me.
