### ISSUE TITLE
Can not have both ipa & apk files within the application directory

### ISSUE THREAD

**Issue by Prav-Patel** [bitstadium/HockeyKit#171]
All,
I can not have both types of app file (.ipa & .apk) within the application directory at the same time.
ipa file always seems to take priority and can be seen irrespective of whether the .apk is present 
so when i look at both devices i will see the app icon on my iOS but nothing on the Android even though i have entered the exact same Url
where as the
apk file will only appear when the ipa is not within the application directory

All i have within the application directory as follows is:
ipa
apk
info.jason
info.plist
icon.png

My aim is to have one of each of my hybrid app files within the directory so i can access at any point.

I have set up a LAMP stack on an Ubuntu Server 14.04 with Apache2 on my EC2 Micro instance within AWS.

I have followed the Server setup instructions. And have fallen on to this blocker which I just cannot solve.

I can download the file using my internet browser on my laptop, but never on my actual devices.
Either Samsung Galaxy S3 4.1.2 or iPod Touch 5G iOS 7.01 - i get a “cannot connect to server “error I am not sure if it is all related?

Has anyone else encountered this issue before? And if so how was it resolved?

I am extremely grateful for any assistance 

Thank you in advance

**Comment by DerAndereAndi** [comment]
This is not supported. You have two options:
1. use separate directories for your Android and iOS releases
2. change the source code yourself to add this functionality

**Comment by Prav-Patel** [comment]
Thank you for your response!

I was under the impression that only one file of each type present in a directory was allowed?

I will follow the installation steps twice creating app directories for each Android & iOS release.

However - Would this mean that in order for the testers to access the app, they would have a choice of 2 Urls to choose from depending on what device they are testing?

Or once i have distinguished an iOS app directory and Android directory within the client/public side and added the corresponding files in each folder:
iOS = (.ipa, info.plist & icon.png) 
Android = (.apk infor.json & icon.png) 
i can direct both iOS testers & Android testers straight to a single public directory Url?

Thank you again for your help.

**Comment by DerAndereAndi** [comment]
One directory holding an app version can only have either an ipa or an apk.

I didn't mean that you should have a "android" directory and an "ios" directory, but have a unique directory holding the versions for android, and one holding the versions for iOS, as described here: https://github.com/TheRealKerni/HockeyKit/wiki/Server#setup-a-new-application

You can not have both ipa and apk files in the same directory.
