### ISSUE TITLE
ios8 - Application Installation Occurs in Background

### ISSUE THREAD

**Issue by jasonirwin** [bitstadium/HockeyKit#173]
As of ios8 when one clicks the install button the installation occurs on the home screen (i.e. in the background) and progress is not obvious to the user. On previous OS versions the browser would be minified and the application icon, with installation progress would be visible to the user.

**Comment by entropid** [comment]
I have the same issue.

**Comment by FabianFrank** [comment]
Not sure if that is fixable in the web. Are we talking about the in-app SDK or the website?

**Comment by entropid** [comment]
I solved it. It was a problem of my server serving the file as chunked.

**Comment by PenaPP** [comment]
I guess I have the same problem in iOS 8 - browser does not minimize, but the application installs on the background.
Is there something I do to make it working exactly the same as on iOS 7?

**Comment by entropid** [comment]
My problem was a misconfiguration of nginx. The file was being sent in chunks and therefore the total size was not in the headers (or was being ignored).

**Comment by PenaPP** [comment]
@entropid Our server doesn't use nginx at all and nobody is capable of telling me if the file is being sent in chunks or not :D How can I test it?

**Comment by entropid** [comment]
You have to look in the headers of the request. Google how to do it for more details. Look at the header “transfer-encoding”.

**Comment by DerAndereAndi** [comment]
Browser not minimizing when accepting installation is a new default behaviour in iOS 8. The user has to manually navigate to the homescreen. There is no workaround for this.

There are other iOS 8 specific issues which we documented for HockeyApp here: http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/known-issues-with-ios-8

**Comment by PenaPP** [comment]
@TheRealKerni Well, I am confused now. @entropid says it works for him :)

**Comment by entropid** [comment]
It works as in it shows the download progression after fixing the problem
with the transfer-encoding header. The browser not minimising is default
behaviour, as already noted, and it happens to me as well. But that was not
my issue.

**Comment by PenaPP** [comment]
@entropid Thank you for the explanation :)
