### ISSUE TITLE
Server: can't see older versions, only the last one

### ISSUE THREAD

**Issue by barzto** [bitstadium/HockeyKit#177]
hey guys,

I'm trying to setup HockeyKit for our app. In my public directory is following dir structure.

```
+- public
  +- com.company.app
    +- version1
      +- app.ipa
      +- manifest.plist
    +- version2
      +- app.ipa
      +- manifest.plist
```

In same way as described here https://github.com/bitstadium/HockeyKit/wiki/Server#distribute-and-manage-multiple-versions. However I'm seeing only last version of the app. 

I tried test stuff from https://github.com/bitstadium/HockeyKit/tree/develop/server/php/tests but with same result.

Is this issue or intended behavior (that was my initial understanding after reading the wiki page but the more I look into code the less I think this is the case)?

Cheers,
-Jan

**Comment by inkuzmin** [comment]
Count me in.

**Comment by taiyab-ctech** [comment]
Did anyone found solution for this issue?

**Comment by FedorShpilenok** [comment]
Anyone?)
