### ISSUE TITLE
How to have different "hidden folders" / manage app permissions

### ISSUE THREAD

**Issue by gizmore** [bitstadium/HockeyKit#178]
We have different customers who should not see their each apps.
How can we easily accomplish that goal?

Regardful
christian

**Comment by ghost** [comment]
Create multiple installations of the tool. One per customer.

**Comment by gizmore** [comment]
Thank you for your quick reply :)
This is quite how i did it, and it´s nice to know it´s a good and easy way.

Regardful
christian
