### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by holtwick** [bitstadium/HockeyKit#18]
You could easily add a RSS feed to the overview page so beta testers could subscribe to it e.g. using Google Reader and get notified on changes. I think a history is not needed, so this could be implemented straight forward. Thanks.

**Comment by DerAndereAndi** [comment]
Your wish is my command ;) Ok, well, kidding aside, just added it :)

**Comment by holtwick** [comment]
Thanks :) Works like a charm.
