### ISSUE TITLE
Cannot Install App, No Error given

### ISSUE THREAD

**Issue by stonemonk** [bitstadium/HockeyKit#181]
New to HockeyKit, trying it out as an alternative to Apple's overly restrictive changes to TestFlight. Got client SDK integrated and server setup.  I can go to app page on laptop and Download Profile and Download App buttons both work.  However, on my iPhone 6, iOS 8.2 test device neither work.  OK I just read that iOS 8 no longer supports manual installation/management of profiles, but that its handled automatically when installing an app.  Fine, but tapping the Install Application button also does nothing at all. If I copy the link, and paste it into Safari it asks "Open this page in 'App Store'" which sounds right, but again, clicking Open does nothing at all.  

[EDIT]:

I figured it out: iOS 8 requires both display-image and full-size-image keys to be present in the plist.

So now it asks me to Install App, and I get a greyed out default app icon on the springboard, but it doesn't seem to ever get downloaded, however the network in use spinner in the status bar remains active.

Ideas?

**Comment by traber333** [comment]
Has anyone come up with a solution for this issue?  I am having the same problem

**Comment by taiyab-ctech** [comment]
Did anyone found solution for this issue?

**Comment by taiyab-ctech** [comment]
I had similar issue and resolved by making all package and image URLs to https :)
