### ISSUE TITLE
Cannot install app, "Cannot connect to <website>"

### ISSUE THREAD

**Issue by haxpor** [bitstadium/HockeyKit#182]
I completely set up the server, and the application page was shown properly.

But after I click "Install Application" on iOS device (iPod Gen 5, iOS 8.3). It shows error pop up saying that "Cannot connect to <website>".

What I think it might relate is as follows
- What is the value should I have in .plist file? Right now I have something like `"https://website.com/subdir1/subdir2/app.ipa"`. I use https:// to access the build.

Any clue or suggestion on this problem?

**Comment by haxpor** [comment]
As investigated, and tested, it seems like HockeyKit doesn't render the Install App, Install Profile button for me. I workaround by creating a simple html page containing a link (itms-service://) and link to what I have set up. It works fine.

Have to look at HockeyKit code for what's going wrong.

**Comment by tfonfara** [comment]
I had the same problem. Checking the plist link (https://website.com/api/2/apps/BUNDLEID?format=plist, replace BUNDLEID with your directory name) gives me the following error:

Strict Standards: Only variables should be passed by reference in .../includes/platforms/ios.php on line 35

Solution is to split up this line:
`$dir = array_shift(array_keys($files[self::VERSIONS_SPECIFIC_DATA]));`

into this:
`$keys = array_keys($files[self::VERSIONS_SPECIFIC_DATA]);`
`$dir = array_shift($keys);`
