### ISSUE TITLE
update Android app

### ISSUE THREAD

**Issue by hannesa2** [bitstadium/HockeyKit#187]
I see my app in Server,
![hockeykit](https://cloud.githubusercontent.com/assets/3314607/12017346/a3370e5a-ad55-11e5-95ee-8cf2e03c34a4.png)
but requesting it from Android

```
https://www.myserver.com/HockeyKit/api/2/apps/com.myapp.xyz?format=json&udid=e093fa9f0f5ce03&os=Android&os_version=4.4.2&device=Android+SDK+built+for+x86&oem=unknown&app_version=5
```

delivers

```
{"result":-1}
```

Apache log has no entry, and honestly I've no idea what's wrong here.
Any hints for me ? 
Thank you

**Comment by ricardolpd** [comment]
looking at the lack of commits and the dangling pull requests, is it right to assume that no one is mainting this project?

**Comment by dashart-ke** [comment]
Looks like the bitstadium guys are only working on their commercial solution:
http://hockeyapp.net/about/
Which is a part of the Microsoft product range now.
