### ISSUE TITLE
Not able to get client side updater to work

### ISSUE THREAD

**Issue by gfontenot** [bitstadium/HockeyKit#2]
I'm having trouble getting this to work on the iPhone side of things.

I have the server set up, and am able to install provisioning profiles and apps from the server, but the app isn't able to see new versions. When I click the "Check for Updates" button, it goes into the process of pulling the info, but doesn't get past this if statement:

```
if ([result compare:@"-1"] != NSOrderedSame && [result compare:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleVersion"]] != NSOrderedSame)
```

Here is the response I get back from the server if I type the same query into Google Chrome:

```
{"profile":1282667060,"title":"Hops","subtitle":null,"result":"0.97"}
```

What exactly have I failed to set up?

**Comment by DerAndereAndi** [comment]
Grab the latest code I uploaded today and try that. Server and client got updated.

**Comment by gfontenot** [comment]
Got the latest code, no dice. Still not getting past that same point.

Am I supposed to keep multiple versions of the app on the server? And I'm assuming the BetaURL has to be the whole path (i.e. http://www.domainname.com/betainstall/index.php)?

Am I supposed to not see the "Check Now" button anymore?

**Comment by DerAndereAndi** [comment]
It will only take the first file of each extension. I did not see a reason for having multiple versions in there yet, makes handling more complicated. The URL does not need to have index.php in the name.

**Comment by gfontenot** [comment]
Fixed. It was a version number issue. Thanks for your patience.
