### ISSUE TITLE
localization issues; had to rename the folders to en/de.lproj

### ISSUE THREAD

**Issue by steipete** [bitstadium/HockeyKit#23]
I don't know why, but localization is not working UNLESS i rename the string directories to en.lproj and de.lproj.

i'm using localization in my app; and using this scheme everywhere - am I doing sth. wrong?

**Comment by steipete** [comment]
Sorry, this was another issue, I used hockey from a static lib.

**Comment by DerAndereAndi** [comment]
ok :)
