### ISSUE TITLE
RSS Feed Link

### ISSUE THREAD

**Issue by holtwick** [bitstadium/HockeyKit#26]
Currently the RSS feed entries all point to 'feed.php', but it should be 'index.php'. To differentiate between versions the URL should become unique e.g. by appending the apps name and version like 'index.php#hockey1.0' (especially in <id>...</id>).

Why? The user likes to be directed from the entry to the landing page to start the download/installation. E.g. Reeder directs me to the empty feed page when clicking on the title.

Thanks Andreas.

**Comment by DerAndereAndi** [comment]
Pushed a fix to the develop branch.

**Comment by felixmueller** [comment]
I habe problems with the image in the RSS feed!

The line in feed.php:
...<?php echo $baseURL."/../".$app[iOSUpdater::INDEX_IMAGE] ?>"...

I replaced it with:
...<?php echo $baseURL.$app[iOSUpdater::INDEX_IMAGE] ?>"...

and it works again.

Cheers, Felix

**Comment by DerAndereAndi** [comment]
Right, stupid me, forgot to adjust that. Thanks for the hint Felix! Pushed to develop branch.

Andreas
