### ISSUE TITLE
No action when choosing to auto-update, crash when checking settings

### ISSUE THREAD

**Issue by gfontenot** [bitstadium/HockeyKit#3]
I have Hockey in my app, and the server side stuff is working great. But on the client side, I am getting the pop-up to alert the user of a new version, but when they say yes, nothing happens. The pop-up is dismissed, and that's all. I have let it sit for a good 20 minutes, and nothing happens. Then, if I go the the beta section of my settings page (which loads BWHockeyViewController), I get a crash. According to the crash report, it's getting EXC_CRASH (SIGABRT) when trying to populate the tableview. Specifically, cellForRowAtIndexPath.

I have the most recent version of the Hockey Client (pulled today)

**Comment by DerAndereAndi** [comment]
Did you set the rootViewController of your UIWindow? If you build for 3.x, make sure to check if UIWindow responds to the selector first. See http://wiki.github.com/TheRealKerni/Hockey/ios-client

Regarding the crash, could you post the stack of the crashing thread please?

**Comment by gfontenot** [comment]
I have the rootViewController set (in the app delegate, calling `[window setRootViewController:rootViewController]`).

I'm also getting this log statement in the console, if this means anything:
    -[NSUserDefaults setObject:forKey:]: Attempt to insert non-property value '{
    notes = "- Version number reverted to 0.9 for testing purposes\n- Workflow changed to redirect to new-beer screen after adding beer\n- Bugfix for lost image data in newer versions (May cause performance issues. Will be removed in future)\n- Bugfix for disappearing rating graphic\n- Bugfix for disappearing Detail header (Watch for this please)\t\n\t";
    profile = 1282667061;
    subtitle = "<null>";
    title = "Hops Lite";
    version = "0.90";
    }' of class '__NSCFDictionary'.

Here's the stack:

```
0   CoreFoundation                      0x31635303 __exceptionPreprocess + 114
1   libobjc.A.dylib                     0x3439a4c4 objc_exception_throw + 40
2   CoreFoundation                      0x31638e0f -[NSObject(NSObject) doesNotRecognizeSelector:] + 98
3   CoreFoundation                      0x316382ab ___forwarding___ + 506
4   CoreFoundation                      0x315c7c50 _CF_forwarding_prep_0 + 48
5   UIKit                               0x34a4e154 -[UITableViewLabel setText:] + 84
6   Hops Lite                           0x000166af -[BWHockeyViewController tableView:cellForRowAtIndexPath:] + 2202
7   UIKit                               0x349d7250 -[UITableView(UITableViewInternal) _createPreparedCellForGlobalRow:withIndexPath:] + 652
8   UIKit                               0x349d6eb4 -[UITableView(UITableViewInternal) _createPreparedCellForGlobalRow:] + 52
9   UIKit                               0x3499d488 -[UITableView(_UITableViewPrivate) _updateVisibleCellsNow:] + 1308
10  UIKit                               0x3499ae48 -[UITableView layoutSubviews] + 208
11  UIKit                               0x34942ab8 -[UIView(CALayerDelegate) _layoutSublayersOfLayer:] + 40
12  CoreFoundation                      0x315bd5c1 -[NSObject(NSObject) performSelector:withObject:] + 24
13  QuartzCore                          0x31d2f624 -[CALayer layoutSublayers] + 184
14  QuartzCore                          0x31d2f2ac CALayerLayoutIfNeeded + 200
15  QuartzCore                          0x31d2ebb8 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 264
16  QuartzCore                          0x31d2e7e0 _ZN2CA11Transaction6commitEv + 284
17  QuartzCore                          0x31d369e0 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 88
18  CoreFoundation                      0x3160924b __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 18
19  CoreFoundation                      0x3160ada5 __CFRunLoopDoObservers + 500
20  CoreFoundation                      0x3160c2fd __CFRunLoopRun + 940
21  CoreFoundation                      0x315b30c3 CFRunLoopRunSpecific + 226
22  CoreFoundation                      0x315b2fd1 CFRunLoopRunInMode + 60
23  GraphicsServices                    0x31acff90 GSEventRunModal + 196
24  UIKit                               0x34935b48 -[UIApplication _run] + 572
25  UIKit                               0x34933fc0 UIApplicationMain + 972
26  Hops Lite                           0x00002a5d main + 88
27  Hops Lite                           0x00002a00 start + 40
```

And the exception:
    -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x3e258704

**Comment by DerAndereAndi** [comment]
Oh, there it is :) Fix is going to be pushed by fabian. Just a minute.

**Comment by fabiankr** [comment]
It took me 4 minutes, sorry.

**Comment by gfontenot** [comment]
Is this what you need?
    {"notes":"- Version number reverted to 0.9 for testing purposes\r\n- Workflow changed to redirect to new-beer screen after adding beer\r\n- Bugfix for lost image data in newer versions (May cause performance issues. Will be removed in future)\r\n- Bugfix for disappearing rating graphic\r\n- Bugfix for disappearing Detail header (Watch for this please)\t\r\n\t","profile":1282667061,"title":"Hops Lite","subtitle":null,"result":"0.90"}

**Comment by gfontenot** [comment]
Y'all are awesome. Thanks for the fast fix.
