### ISSUE TITLE
ipa file having spaces cannot be installed

### ISSUE THREAD

**Issue by DerAndereAndi** [bitstadium/HockeyKit#31]
If the ipa file has spaces in the filename, the installation process doesn't work.

**Comment by ghost** [comment]
Probably related: Folder names on The Server that contain a trailing space also prevent IPA Download. This could possibly be fixed by a "simple" rtrim, i may provide a pull request soon.

**Comment by jacobweber** [comment]
Just ran into this issue. Seems like you could fix it by URL-encoding the filename.
