### ISSUE TITLE
server PHP script corrupts IPA file during download

### ISSUE THREAD

**Issue by tomkfischer** [bitstadium/HockeyKit#39]
Not sure if this is really a bug in Hockey or just in my server setup.

Whenever I try to pull the IPA file via the "Download Applicaiton" link,
the server script mangles it by inserting line breaks at the beginning of the file (offset 0000:  0x0A 0x0A ...), truncating two null bytes at the end. 

I double checked that the file on the server hasn't been corrupted before (same sha1 hash). Downloading it directly via it's absolute URL also works fine.

It really seems like the php script is "injecting" those two extra 0x0A0A bytes and truncating the tail accordingly.

Any ideas?  

used version: e7818489...

**Comment by tomkfischer** [comment]
PS: The problem might potentially be related to this kind of similar issues:
http://stackoverflow.com/questions/1560075/zip-files-get-corrupted-by-ie

**Comment by Soryu** [comment]
I’m pretty sure it is related to PHP output buffering and some line breaks in the PHP code. You seem to have disabled output buffering in your PHP configuration, so the linebreaks at the end of some PHP files (after the closing `?>`) get sent to the client.

**Comment by tomkfischer** [comment]
Hmm, but it looks like output buffering _is_ enabled:

/etc/php.ini:146:output_buffering = 4096 

I haven't disabled it anywhere else and the Hockey version I use is a clean, unmodified checkout of e78184890... (aka 1.0)

**Comment by Soryu** [comment]
OK, in that case can you please reopen the issue? I’ll try to look into it.

**Comment by tomkfischer** [comment]
I think I don't have permission on this repo to re-open an issue. (...or I'm just too stupid to find the button.)
