### ISSUE TITLE
[issue #38 re-opened] server PHP script corrupts IPA file during download

### ISSUE THREAD

**Issue by tomkfischer** [bitstadium/HockeyKit#40]
Not sure if this is really a bug in Hockey or just in my server setup.

Whenever I try to pull the IPA file via the "Download Applicaiton" link,
the server script mangles it by inserting line breaks at the beginning of the file (offset 0000: 0x0A 0x0A ...), truncating two null bytes at the end.

I double checked that the file on the server hasn't been corrupted before (same sha1 hash). Downloading it directly via it's absolute URL also works fine.

It really seems like the php script is "injecting" those two extra 0x0A0A bytes and truncating the tail accordingly.

Any ideas?

used version: e7818489...

see also: https://github.com/TheRealKerni/Hockey/issues/closed/#issue/39

**Comment by Soryu** [comment]
OK, I can’t really reproduce it without . Can you please enable `error_reporting`/`log_errors`/`display_errors` in the PHP config and check for these or any other error message?

```
Warning: Cannot modify header information - headers already sent by (output started at server/php/public/config.php:6) in server/php/includes/main.php on line 353

Notice: ob_flush(): failed to flush buffer. No buffer to flush in server/php/includes/main.php on line 46
```

If that does not work, you can provide me with more detailed info about your system & OS, version of PHP and maybe even the `php.ini` (with sensitive info removed) file. Just mail it to soryu2@gmail.com.

**Comment by tomkfischer** [comment]
D'oh!  

Found the problem: accidentally added two line feeds (=0x0A0A) at the end of server/php/public/config.php
