### ISSUE TITLE
HTTPS issues

### ISSUE THREAD

**Issue by tibo** [bitstadium/HockeyKit#42]
Hi

I've got some issues on an hockey server installed on an HTTPS server (with a real certificat, not self-signed).
When I touch the button "install" on an iPhone nothing happen.

I try to copy the link and I've got somethink like:
itms-services://?action=download-manifest&url=http%3A%2F%2Fmy_server.com%3A443%2Findex.php
(I also get it by displaying itms-services://?action=download-manifest&amp;url=<?php echo urlencode($baseURL . 'index.php?type=' . iOSUpdater::TYPE_APP . '&bundleidentifier=' . $app[iOSUpdater::INDEX_DIR]) ?>)

Notice the "http..... :443" instead of "https..."

So I made some modification in the index.php for the $protocol and $port variable:

$protocol = $_SERVER['HTTPS']==on?'https':'http';

$port = in_array($_SERVER['SERVER_PORT'],array(80,443))?'':':'.$_SERVER['SERVER_PORT'];

the install did start but finaly fail and ask for retry (which also fail)

**Comment by DerAndereAndi** [comment]
This is most probably because the plist file does the same mistake. We'll look into it.

**Comment by Soryu** [comment]
Do you have `display_errors` enabled and the `error_reporting` set to include notices in your production PHP configuration? See also http://de3.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting to find out more about that.

I just pushed a fix that might help you: https://github.com/TheRealKerni/HockeyKit/commit/35230a31f355fb7c1cd2bc5b9128efa2ec97561f

**Comment by tibo** [comment]
As Andreas tell me, the V2 alpha solve my problem.

Thanks!
