### ISSUE TITLE
RewriteRule doesn't work if installed in a subdirectory

### ISSUE THREAD

**Issue by chrispix** [bitstadium/HockeyKit#43]
I'm running the feature/redesign branch, and I have it installed under /builds on my web server. Trying to load the application from the web page results in a 404, with this error in my log:

File does not exist: /path/to/webroot/builds/api, referer: http://myserver.com/builds/

It also seems that the .\* pattern prevents the stats page from displaying. 

Changing the RewriteRule in https://github.com/TheRealKerni/HockeyKit/blob/feature/redesign/server/php/public/.htaccess to the following fixes both issues:

RewriteRule api/.\* /builds/index.php [L]

I don't know if there's a way to write the RewriteRule more generically so it'll work in any subdirectory.

**Comment by DerAndereAndi** [comment]
The rewrite rule works great on my test system, where it is also installed under a subdirectory like http://myserver.com/apps/beta/

I did not have to change the rewrite rule, so this sounds a little strange right now.

Regarding the stats page, the rewrite rule makes it currently impossible to user /stats/ but you have to invoke it via /stats/index.php instead. This is surely something we should fix.

**Comment by chrispix** [comment]
Unfortunately my web host doesn't support RewriteLog to see why it isn't matching. I'll try testing on a local apache install and see if I can reproduce it.

**Comment by jeanregisser** [comment]
I thought I had the same problem, it appeared it was just the .htaccess that was ignored as the main httpd.conf had AllowOverride None for the parent directory.

**Comment by skycoders** [comment]
I also face an issue with the rewrite rule. Don't know what my hoster is doing. I figured out the following:
- If I put public files in a subdirectory, it works
- If I put public files in the top level directory of a configured subdomain, it crashes, except I add /index.php to the URL
- If I remove the .\* rewrite rule, everything works fine.

There must be some issue on certain Apache and PHP configurations. On another server, everything works fine...

**Comment by codedifferent** [comment]
I also encountered the problem when installing the server on a webserver on 1and1 / 1und1 ...

``` apache
RewriteRule .* index.php [L]
```

... did not work properly when I installed the HockeyKit server within a subDirectory. My workaround:

``` apache
RewriteRule .* /mySubDirectory/index.php [L]
```

P.S. for those working with 1&1 servers ... don't forget to include the following lines in your .htaccess file to enable php5 ;-)

``` apache
AddType x-mapp-php5 .php
AddHandler x-mapp-php5 .php
```

**Comment by tspecht** [comment]
Thanks, that solved my problem....can't thank you enough :D

**Comment by skycoders** [comment]
In order to get it working in the subdomain configuration of DomainGo, I had to add

```
RewriteRule /pathofmysubdomaindirectory/.* index.php [L]
RewriteRule api/.*  /index.php [L]
```

In this case I have a subdirectory on the server, which is the root directory of my configured subdomain. But with these two rules it is working :)
