### ISSUE TITLE
Select a version to download

### ISSUE THREAD

**Issue by chrispix** [bitstadium/HockeyKit#48]
I've got your multi-version support set up, but I'd like users who have access to multiple versions to be able to select a version to download, for example to choose between a release candidate and a future release version.

**Comment by DerAndereAndi** [comment]
You would have to fork the code and add the functionality. This would also require quite some work on the device specific UI web frontends.

As this is mainly for beta testing, I don't see the real use of it. AppStore versions should be the stable versions. If you want an additional stable version, make another build with another bundle identifier. You could do the same for future release versions, if they are experimental, use another bundle identifier.

**Comment by chrispix** [comment]
I was thinking of it mainly in the PHP UI, not necessarily on-device. But I think you're right that a different app ID is the better approach for this.
