### ISSUE TITLE
Providing individual pages for each or selected applications

### ISSUE THREAD

**Issue by dvmorris** [bitstadium/HockeyKit#50]
In the documentation.mdown file, I see the following line:
- By default all available applications appear in a single web page, but there is also an option to provide individual pages for each or selected applications.

Where is this configuration setting? I can't seem to find it.

Thanks,
Dave

**Comment by DerAndereAndi** [comment]
Check the wiki at https://github.com/TheRealKerni/HockeyKit/wiki/Server and search for the part _Hiding application from main web page_

**Comment by dvmorris** [comment]
Ah, I see. That makes sense. So I would need to provide my QA team with those specific URLs. That makes sense. 

Thanks,
Dave
