### ISSUE TITLE
Sorting apps by version number

### ISSUE THREAD

**Issue by iwleonards** [bitstadium/HockeyKit#54]
I would like to sort the available apps by the version number so that the latest app will be displayed at the top of the page.  Is there a way to do this currently?

**Comment by DerAndereAndi** [comment]
This is currently not possible.

The function `public function show($appBundleIdentifier)` in `main.php` would have to be modified to allow custom sorting of the application list.

**Comment by iwleonards** [comment]
Ok thanks for the tip I added the following to the function `public function show($appBundleIdentifier)` in `main.php` just before the call to `closedir($handle)`. 

```
$this->applications = Helper::array_orderby($this->applications, self::INDEX_VERSION, SORT_DESC);
```
