### ISSUE TITLE
JSON.inc crashing or in a loop

### ISSUE THREAD

**Issue by natedavis** [bitstadium/HockeyKit#56]
I am trying to embed the HockeyKit development branch from today (May 12th 2011) into an iOS app...

All seems to be well, as the proper URL gets called but the JSON.inc file has an error:

There was an error parsing the JSON document. The document may not be well-formed.
Document contents:

Here is the Access Log from Apache:
10.0.5.55 - - [12/May/2011:16:35:44 -0600] "GET /apps/api/2/apps/com.medonemarketing.MobileAxis?format=json&udid=1493E89E-1B3E-59C0-B8D2-BB7CF69A5975&app_version=3&os=i64&lang=en&usage_time=0&first_start_at=05%2F12%2F2011 HTTP/1.1" 200 -

Error Log:
[Thu May 12 16:36:44 2011] [error] [client 10.0.5.55] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /www/ioscrash.medonecapital.com/includes/json.inc on line 30

I tried changing the PHP max timeout to 300 sec, but it still hung until the PHP Fatal Error.

I am using Xcode 4.0.2 with SDK 4.3...

Let me know what else I can provide to get this fixed...

Thanks

**Comment by DerAndereAndi** [comment]
Which PHP Version are you using on the server? I guess it may be PHP4, can you switch it to PHP5? It would then use the PHP build in json encode method.

That function is calling itself in line 40 and 45 in json.inc, if it is encoding hierarchical data.

What you could do is add `echo $content;exit();` in line 136 in `helper.php` and invoke the URL from your browser. You'll then see the PHP structure it tries to encode into JSON. Maybe that helps finding the problem.

**Comment by natedavis** [comment]
Thanks for getting back with me...

I am running CentOS 5, and when I run php -v I get this:

PHP 5.1.6 (cli) (built: Nov 29 2010 16:47:37) 
Copyright (c) 1997-2006 The PHP Group
Zend Engine v2.1.0, Copyright (c) 1998-2006 Zend Technologies
    with Zend Extension Manager v1.2.2, Copyright (c) 2003-2007, by Zend Technologies
    with Zend Optimizer v3.3.3, Copyright (c) 1998-2007, by Zend Technologies

So, I am running php 5...  So, I added the echo $content like you asked me too... When I navigate to:

http://ioscrash.medonecapital.com/apps/api/2/apps/com.medonemarketing.MobileAxis?format=json&udid=31fc238ac07879b88ef5de939819c52087986e3d&app_version=3&os=iOS&os_version=4.3.3&device=iPhone3%2C1&lang=en&usage_time=60&first_start_at=05%2F12%2F2011

All that is returned is "Array" so, I suspect I am missing something...  Any other pointers on where I can look? I must be missing something on my system that will not let it parse...

**Comment by DerAndereAndi** [comment]
Ok, that needs a `print_r($content)` instead to show the content of the array instead of using the `echo`

**Comment by DerAndereAndi** [comment]
Ok, that looks better. My only guess would be, that it breaks with the `<br/>` in your release notes. What happens if you remove that?

**Comment by natedavis** [comment]
OK, so I removed the CR from the HTML file....  Nothing... that <br/> is coming from somewhere... When I nano -w MobileAxis.html it is not in there... Just some text, and I verified there are no CR in the file...

**Comment by DerAndereAndi** [comment]
In general, this is a very old PHP version you are running. I would recommend upgrading CentOS to get at least PHP 5.2. Other than that you could check the php log if there is additional info in there.

**Comment by DerAndereAndi** [comment]
OK, the `<br/>` was inserted by the system behind the title. Then rather just remove the readme for testing. But I highly suggest to upgrade, this is now just trying and failing until we may be lucky.

**Comment by natedavis** [comment]
What version of PHP do you use in your development environment? Just want to upgrade me to the latest that has been tested....

**Comment by natedavis** [comment]
OK, so even after removing the .html file for the Release notes, it was a no go... Same problem... I am going to update my PHP install, and go from there... I will post back if that works.

**Comment by natedavis** [comment]
Success...  - I upgraded to PHP 5.3.6, and all is well. So, maybe in the readme something should be stated about a min PHP version...  Thanks for your help...  I used the remi repo to upgrade my CentOS 5 to the latest mysql and php...

**Comment by DerAndereAndi** [comment]
Ok, nice. I'll add it with the next commit. Glad you got it working!
