### ISSUE TITLE
Use standard language codes in bundle

### ISSUE THREAD

**Issue by rsebbe** [bitstadium/HockeyKit#65]
Noticed the bundle has English.lproj and German.lproj. Could that be changed to en.lproj & de.lproj instead? (my app check scripts are a bit picky)

**Comment by DerAndereAndi** [comment]
Sure, will do with the next update.

**Comment by rsebbe** [comment]
Great! BTW, I'm very impressed by the whole experience of HockeyApp.net (the web app, the value for developers). You guys rock!

**Comment by DerAndereAndi** [comment]
This has been fixed on June 18th.
