### ISSUE TITLE
ipa File in subfolder is being linked wrong

### ISSUE THREAD

**Issue by MarcoGlauser** [bitstadium/HockeyKit#73]
We have several clients and have therefore stored our apps in different folders. This works until the download of the app. The URL in the plist file points to the main public folder. And because of the mod_rewrite it gets redirected to index.php.
so the app is for example in
http://server/clients/client1/bundleidentifier/app.ipa
but the generated plist links to
http://server/bundleidentifier/app.ipa

I tried some workaround and actually got the right path but that didn't work either.

**Comment by DerAndereAndi** [comment]
Hi,

I don't think this is working. There is a fork of the version 1 code which provides a multi store concept available at https://github.com/pyby/Hockey

For Version 2 this is not available yet. Adding subfolders doesn't seem to be a clean solution, this the API has to change for that. Also I see clients rather as metadata, so would rather introduce a new file attribute, like a file named "ClientA.client" within each app, and then add a public page listing all clients apps by invoking something like myserver/beta/ClientA and also remove those apps from the public root page of course. Feels like this could be the right approach.

Best
Andreas
