### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by benmonro** [bitstadium/HockeyKit#75]
It would be nice if HockeyKit could catch, symbolocate and publish crash reports to the server...

**Comment by DerAndereAndi** [comment]
Hi,

https://github.com/TheRealKerni/QuincyKit does that.

Andreas

**Comment by benmonro** [comment]
Andreas,  does this include android?  looks like QuincyKit only supports ios/mac...

**Comment by DerAndereAndi** [comment]
No, QuincyKit is iOS/Mac only indeed. HockeyKit does include the android crash reporting part, because we did not want to split it into two frameworks. The effort of adding one frameworks is big already. Though there is no backend for this data yet available except our hosted solution at http://hockeyapp.net

Andreas

**Comment by amitbattan** [comment]
Can I setup my own server for the crash reports.
as like hockey server for manage applications

**Comment by DerAndereAndi** [comment]
As mentioned above, the QuincyKit server does that, but it works only for iOS and Mac crash reports. HockeyKit server component is not meant and also not designed for that.

**Comment by amitbattan** [comment]
Yes I am checking it.. 

and also I am getting "Cannot connect to Server" in HocketKit while installing app on device.

I have add the app.ipa and TestHockey-Info.plist
and link of download which I getting from webpage is of app.ipa

**Comment by DerAndereAndi** [comment]
Make sure you followed all instructions shown here https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/README.mkdown and here https://github.com/TheRealKerni/HockeyKit/wiki/Server and that your .htaccess contains the correct rewrite rules. If this doesn't work, it is most likely a problem with your server setup.

**Comment by amitbattan** [comment]
I have check .. can you please specify me what should I have to in . htaccess file 

my public/.htaccess file contains

```
# REWRITE RULES
<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteRule ^stats/$ stats/index.php [L]

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .* index.php [L]

</IfModule>

# MIME TYPES
<IfModule mod_mime.c>
    AddType application/octet-stream .ipa
    AddType application/vnd.android.package-archive .apk
    AddType text/xml .plist
</IfModule>
```

**Comment by DerAndereAndi** [comment]
This looks ok to me, but some server require other settings or changes. I can't help you on that, you need to check the server documentation. Also make sure that the plist has "**URL**" entered. I can only give this generic advice, sorry.

**Comment by amitbattan** [comment]
I have not entered the URL in plist, which URL for which Key

**Comment by DerAndereAndi** [comment]
https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/README.mkdown says:

```
* Select "Share application"
* Select "Distribute for Enterprise..."
* Fill out the URL field and type "__URL__" (important !!)
* Enter a title, this will be shown in the web interface and on the client
* Version number will be taken automatically from the generated plist file
```
