### ISSUE TITLE
iOS 5 iPad not supported

### ISSUE THREAD

**Issue by iosdeveloper** [bitstadium/HockeyKit#76]
Hey,

I'm using the latest files from master branch.
Unfortunately, it seems like an iOS 5 iPad is detected as not supported.
Which lines do I have to change to make it work?

Thanks!

**Comment by steipete** [comment]
Use the develop branch, it's _much_ improved over master branch and iOS5 is supported here.

**Comment by iosdeveloper** [comment]
Mh, I would like to stay on the latest stable release. I noticed, that the master branch wasn't updated for some months, will it sometimes receive some merges from development branch (which is default branch now?). Also some branches named in README do no longer exist.

**Comment by iosdeveloper** [comment]
However, this issue can be closed now. Found this commit, which helps: http://github.com/TheRealKerni/HockeyKit/commit/f86fd72b61d82c4e1767ca5a58e982e9bf53279b

**Comment by steipete** [comment]
Don't worry - the tagging is imminent. I have many apps in the store that use the dev branch, it's perfectly stable.

**Comment by iosdeveloper** [comment]
Issue fixed, opened pull request: http://github.com/TheRealKerni/HockeyKit/pull/77
