### ISSUE TITLE
Beta Automatisation fails

### ISSUE THREAD

**Issue by iosdeveloper** [bitstadium/HockeyKit#78]
The changes I made to "Beta Automatisation.sh":

ftpUsername="username"
ftpPassword="password"
ftpServerDirectoryPath="server.tld/directory"

scpUser="username"
scpHost="server.tld"
scpPath="/directory"

The error I receive everytime I build my app:

Uploading MyApp.ipa and MyApp.plist to server.tld...
ssh: connect to host server.tld port 22: No route to host
lost connection
ssh: connect to host server.tld port 22: No route to host
lost connection

Any ideas what's going wrong?

**Comment by iosdeveloper** [comment]
After changing uploadMethod to ftp, everything works fine.

**Comment by DerAndereAndi** [comment]
Then the reason is probably that your server does not have SSH running.
