### ISSUE TITLE
Cannot find protocol declaration for 'BWHockeyManagerDelegate'

### ISSUE THREAD

**Issue by iosdeveloper** [bitstadium/HockeyKit#79]
Building the develop or master branch iOS demo with AppStore_Distribution config fails:

`In file included from /Users/username/Downloads/TheRealKerni-HockeyKit-553a0c4/demo/iOS/Classes/HockeyDemoAppDelegate.m:9:
/Users/username/Downloads/TheRealKerni-HockeyKit-553a0c4/demo/iOS/Classes/HockeyDemoAppDelegate.h:17:69: error: cannot find protocol declaration for 'BWHockeyManagerDelegate'
 @interface HockeyDemoAppDelegate : NSObject <UIApplicationDelegate, BWHockeyManagerDelegate> {
                                                                     ^
1 error generated.`

All other configs do work.

**Comment by DerAndereAndi** [comment]
The demo app is not meant to do that.

If you are implementing a delegate method in your own app, you would have to change the interface declaration to something like this:

```
#if !defined (CONFIGURATION_AppStore_Distribution)
@interface HockeyDemoAppDelegate : NSObject <UIApplicationDelegate, BWHockeyManagerDelegate>
#else
@interface HockeyDemoAppDelegate : NSObject <UIApplicationDelegate>
#endif
{
```

And also `#ifdef` the delegate methods as a whole so they won't be part of the app store build.

Hope this helps
Andreas

**Comment by iosdeveloper** [comment]
I'm fixing it right now and will provide a pull request, so others see how it's meant to do in their own apps.
