### ISSUE TITLE
HockeyKit 2.0 ~ Settings aren't saved

### ISSUE THREAD

**Issue by iosdeveloper** [bitstadium/HockeyKit#82]
Just upgraded to latest stable HockeyKit release (2.0).
Now, the user settings (Send User Data/Send Usage Data) aren't saved.
As soon as I kill my app in multitasking bar and reopen it, the settings are back to default.
Instead, Check For Update is properly saved and restored.

**Comment by iosdeveloper** [comment]
It appears on both Phone and Pad. Have I missed any new configuration?

**Comment by DerAndereAndi** [comment]
Thanks for the hint, must have been there for a long time unnoticed. Just pushed a fix to the development branch.

**Comment by iosdeveloper** [comment]
It's now working properly. Why not push the fix to the master branch also?

**Comment by iosdeveloper** [comment]
User data is uploaded to server even if the user has disabled it in settings.
Also, usage time shows high, wrong value (~100-200) [only, if user has disabled user data upload].
Please take a look at this screenshot: http://cl.ly/8zwX

**Comment by DerAndereAndi** [comment]
This is now fixed. The values on the stats page where correct, those where shown in seconds. This is now shown in hours minutes seconds instead.

**Comment by iosdeveloper** [comment]
Everything seems to be fine now. Thanks ;)
