### ISSUE TITLE
Server not recognising iOS 5 devices

### ISSUE THREAD

**Issue by Jonno** [bitstadium/HockeyKit#84]
I have a server that does not recognise iOS 5 devices. It uses the develop branch.

**Comment by DerAndereAndi** [comment]
Hi Jonno,

what do you mean it does not recognize iOS5 devices? The download page is not appearing? If so, make sure you are really really using the latest code. This has been fixed some time ago: https://github.com/TheRealKerni/HockeyKit/commit/f86fd72b61d82c4e1767ca5a58e982e9bf53279b

Andreas

**Comment by Jonno** [comment]
Hi,

it's all good now. You were correct about the old version.

Cheers J
