### ISSUE TITLE
Does not work together with basic auth protection

### ISSUE THREAD

**Issue by googelybear** [bitstadium/HockeyKit#85]
Hi,

I installed hockey kit for my android app and setup basic auth in my apache config to protect my /var/www/hockey-kit directory, so that only authorized users can download my app. I am using apache as webserver on a linux machine.

Once I activate the basic auth protection access to the main download page is possible after entering the correct credentials however the download then fails on all android devices I tested so far with a "Download unsuccessful" error (shown in the Download Manager) - no further details given. When I deactivate basic auth again it works fine again.

Here's a look in my apache config:

&lt;Location /hockey-kit&gt;
                Options All
                LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so       

```
            AuthType Basic
            AuthName "Login"
            AuthUserFile /opt/hockey-kit/users
            Require valid-user
```

&lt;/Location&gt;

Inspecting the apache access log shows that the .apk file is somehow accessed by android without passing the entered credentials along (there are 3 downloads in total). Here's a snippet from the log of what happens when I click on the download link:

myserver.com:80 62.12.140.99 - - [11/Aug/2011:10:47:22 +0200] "GET /hockey-kit/api/2/apps/myapp?format=apk HTTP/1.1" 401 614 "http://myserver.com/hockey-kit/" "Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Nexus S Build/GRJ22) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
myserver.com:80 62.12.140.99 - mono [11/Aug/2011:10:47:22 +0200] "GET /hockey-kit/api/2/apps/myapp?format=apk HTTP/1.1" 200 31196 "http://myserver.com/hockey-kit/" "Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Nexus S Build/GRJ22) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
myserver.com:80 62.12.140.99 - - [11/Aug/2011:10:47:23 +0200] "GET /hockey-kit/api/2/apps/myapp?format=apk HTTP/1.1" 401 786 "-" "Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Nexus S Build/GRJ22) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"

Am I doing something wrong here or is this a known bug? How do you suggest to protect a hockey kit instance?

**Comment by DerAndereAndi** [comment]
Hi,

as I understand it this is a problem of the Android browser not passing the authorization properly. So I would suggest make the subdirectory of your app private, then the app won't appear on the main page. And you can send testers the link to the app specific page.

Check "Hiding application from main web page" on this wiki page: https://github.com/TheRealKerni/HockeyKit/wiki/Server
- Andreas

**Comment by googelybear** [comment]
I totally agree with you, my conclusion was the same. Thanks for providing a workaround (even though it's much less secure this way). It would still be cool if this could be 'enabled' (I don't know how much you guys can do with the current way of re-writing/modifying the URLs. Is this really needed?).

One thing I noticed is that basic auth works just fine in Firefox.

**Comment by jriker1** [comment]
I am having a similar problem with version 2. I am using iOS and works fine. When I enable basic authtype it asks for credentials and shows the main app page. When I click to download the app thru the manifest file link it pops up a challenge box again, then again. Then shows the app to download on the iPad main screen and two more challenges again.  Only way I found around it was to leave the site wide open and directly protect the IPA only thru the .htaccess file. But have to directly reference each IPA individually. Cluggy.  Thoughts?

**Comment by FabianFrank** [comment]
This is a problem with iOS. The plist and ipa itself are not downloaded by the browser, but by the store app. The store app does not send any cookies or http auth that the browser has. One workaround is to use a one time token (like a CSRF token) and append that to the URLs for the plist when serving the page (and to the ipa when serving the plist) and then only serve them if the token is present, which means you know the user had visited the protected main page before and thus was logged in.
