### ISSUE TITLE
Lost in translation

### ISSUE THREAD

**Issue by vguerci** [bitstadium/HockeyKit#87]
I guess some merge failed, French.lproj & nl.lproj should not be there :
https://github.com/TheRealKerni/HockeyKit/tree/527c9424221c5ebc90bac1ee06423bf4e443ac89/client

**Comment by DerAndereAndi** [comment]
Oh right, thanks for the hint. I jst removed those files, since they did belong to the 1.x version. Must have been sitting there some weeks already.

**Comment by vguerci** [comment]
You're welcome! But take care that these wasn't sitting there, or maybe in your working directory, and were added yesterday during merge.
