### ISSUE TITLE
Safari could not install a profile due to an unknown error

### ISSUE THREAD

**Issue by dvmorris** [bitstadium/HockeyKit#94]
I'm on an iPad 1 with the iOS 5 GM from yesterday, and when I click the "install profile" link on my HockeyKit builds, I get the following error in Safari:

Cannot Install Profile
Safari could not install a profile due to an unknown error

Has anyone seen this before? Any ideas what's causing it?

Thanks,
Dave

**Comment by ashtom** [comment]
Hi Dave,

I can reproduce this error message if the UDID of the device is not included in the provisioning profile. Can you check if your iPad 1 is actually part of your profile?

Cheers,

Thomas

**Comment by dvmorris** [comment]
It turns out that this may be caused by the profile being expired. I wonder why Safari can't just say "Hey, it's expired."

Thanks for your help,
Dave
