### ISSUE TITLE
Fix for iOS 5

### ISSUE THREAD

**Issue by imclean** [bitstadium/HockeyKit#95]
Inside the DeviceDetector.php change the if statement for checking the iPhone to this:

if (strpos($agent, 'iPhone OS 4') !== false) {
                self::$isNewIOSDevice = true;
            } else if (strpos($agent, 'iPhone OS 5') !== false) {
                self::$isNewIOSDevice = true;
            } else {
                self::$isOldIOSDevice = true;
            }
 you could do the same for iPad also if you wish.

Cheers.

Iain

**Comment by DerAndereAndi** [comment]
This was already done back on June 24th in a more general approach: https://github.com/TheRealKerni/HockeyKit/commit/f86fd72b61d82c4e1767ca5a58e982e9bf53279b

**Comment by imclean** [comment]
not for ios 5 it wasn't, just trying to contribute.

**Comment by DerAndereAndi** [comment]
Hi,

I know you are trying to contribute. Thanks for that. But check the commit again, that code also covers iOS5. This is really really already covered.

Andreas
