### ISSUE TITLE
problems with iOS5

### ISSUE THREAD

**Issue by gia-sys** [bitstadium/HockeyKit#96]
Hi,

I've got problems with the app installation on an iOS5 device.
With iOS4 everything is working!!!

When i start the installation on the iOS5 device i've got the following error:
Unable to download
"my application" could not be downloaded at this time.

I have already the new devicedetector.php

(  
 $agent = $_SERVER['HTTP_USER_AGENT'];

```
    if (strpos($agent, 'iPad') !== false) {
        if (strpos($agent, 'OS 3') !== false) {
            self::$isOldIOSDevice = true;
        } else {
            self::$isiPad4Device = true;
        }
    } else if (strpos($agent, 'iPhone') !== false) {
        if (strpos($agent, 'iPhone OS 3') !== false) {
            self::$isOldIOSDevice = true;
        } else {
            self::$isNewIOSDevice = true;
        }
    } else if (strpos($agent, 'Android') !== false) {
        self::$isAndroidDevice = true;
    }
```

)

**Comment by DerAndereAndi** [comment]
Are you using an AdHoc provisioning profile? It seems team/development provisioning profiles do not work any more in iOS5.

**Comment by gia-sys** [comment]
Thanks for your answer.
It's an adhoc provisioning profile!
When i use iTunes to put the application on the device it works!

Maybe it's my plist file???

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>items</key>
    <array>
        <dict>
            <key>assets</key>
            <array>
                <dict>
                    <key>kind</key>
                    <string>software-package</string>
                    <key>url</key>
                    <string>http://xxx:8080/xxx/xxx.ipa</string>
                </dict>
                <dict>
                    <key>kind</key>
                    <string>display-image</string>
                    <key>needs-shine</key>
                    <false/>
                    <key>url</key>
                    <string>http://xxx:8080/xxx/xxx.png</string>
                </dict>
                <dict>
                    <key>kind</key>
                    <string>full-size-image</string>
                    <key>needs-shine</key>
                    <false/>
                    <key>url</key>
                    <string>http://xxx:8080/xxx/1314368579/Icon.png</string>
                </dict>
            </array>
            <key>metadata</key>
            <dict>
                <key>bundle-identifier</key>
                <string>de.gia.biapps</string>
                <key>bundle-version</key>
                <string>2.1.2</string>
                <key>kind</key>
                <string>software</string>
                <key>title</key>
                <string>my application</string>
            </dict>
        </dict>
    </array>
</dict>
</plist>
```

**Comment by gia-sys** [comment]
sorry, i can't paste it correctly

**Comment by DerAndereAndi** [comment]
I corrected it :) You need to use the correct markdown syntax for xml and code snippets :)

That plist should be generated by the HockeyKit server. So what happens exactly? Does it start downloading? When does the error message appear?

**Comment by gia-sys** [comment]
The error message appear when the download starts.
I see the icon on the homescreen, the device tries to download the application and then i get the error.

**Comment by DerAndereAndi** [comment]
Well, maybe check the console log on the device if there is any more hints. It seems it is trying to download the app, and the URL is not working. Could you check that the URL of the generated plist works in your desktop browser?

**Comment by gia-sys** [comment]
yes, that's working -  the URL is correct.

ok, i'll try to check the console log.

**Comment by lando20** [comment]
I have the same problem, but is not related to iOS5. I'm testing on iPad 2 with iOS 4.3 and still can see "Cannot connect to..." when I press "Install Application". My hockey log shows:
_
Router (Router)::init :: 92 /
Router (Router)::routeV1 :: 271 arg `bundleidentifier` not set
Router (Router)::routeV1 :: 272 arg `type` not set
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
_

Please give me any hint as I'm out of ideas

**Comment by florianbachmann** [comment]
perhaps it relates to this error?
`[Fri Oct 21 17:09:10 2011] [error] [client 92.50.101.225] PHP Notice:  Undefined index: subtitle in /home/xxx/hockeypublic/index.php on line 244
[Fri Oct 21 17:09:12 2011] [error] [client 92.50.101.225] PHP Warning:  mkdir(): Permission denied in /home/xxx/hockeyincludes/logger.php on line 28`

Ignore it, my fault.
I echoed the path and created the log dir under the user dir, so this error is gone,
but unfortunately it still doesn't install under iOS5.

Now it get something similar to lando20:
`Router (Router)::init :: 92  /apps/de.mybundleidentifier
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
Router (Router)::init :: 92 /api/2/apps/de.mybundleidentifier?format=plist
Router (Router)::run :: 226 arg `authorize` not set
iOSAppUpdater (AppUpdater)::getApplicationVersions :: 296   arg `lang` not set
 (iOSAppUpdater)::deliverIOSAppPlist :: 183 arg `udid` not set
Router (Router)::init :: 92 /apps/de.mybundleidentifier
AppUpdater (AppUpdater)::getApplicationVersions :: 296  arg `lang` not set
Router (Router)::init :: 92 /api/2/apps/de.mybundleidentifier?format=plist
Router (Router)::run :: 226 arg `authorize` not set
iOSAppUpdater (AppUpdater)::getApplicationVersions :: 296   arg `lang` not set
 (iOSAppUpdater)::deliverIOSAppPlist :: 183 arg `udid` not set`

under iOS4 all works well (and in iOS 5 see next line)

ignore it again, i recreated it thee times, and i don't know what i've changed, but now all works fine :-)

**Comment by darogina** [comment]
Is there any update to this issue?  I am having the exact same problem as the OP except I do not have any errors in my server logs.  In my device console log I see errors pertaining to the thumbnail not being able to be saved and unable to extract archive.  I have tried installing with both In-House and Ad-Hoc profiles but still no luck.  Any Ideas?

**Comment by bbguitar** [comment]
Yes this is the same for me.. Anybody got a solution for this.

**Comment by lando20** [comment]
I fix my solution. Fix was pretty simple. I had hockey install under url like this: www.mycompany.com/hockey/

after adding to.htaccess line:
RewriteBase /hockey/
Everything work fine since now.

**Comment by DerAndereAndi** [comment]
Sounds like we should come up with some script for testing the rewrite rules.

**Comment by lando20** [comment]
Adding:
RewriteBase /
to .htaccess and some comment, how to setup this would be also nice :).

**Comment by bbguitar** [comment]
Adding rewrite base has not fixed the problem. I'll have to do a bit more experimenting to try and find out where its breaking.
It might just be the build directory bundle name mismatching somewhere but there's not easy way of debugging this.

**Comment by erickyellott** [comment]
My guys in the field are also getting this exact same error. I've installed the app on 5 different iPads without a problem, but 2 of my field guys get the 'cannot download at this time' message. One guy had to reset all his content and settings to get it to download, and my other guy did the same but still gets the error. Using an In House Distribution Provisioning Profile and iOS5 as well.

**Comment by andreaspollak** [comment]
I had the same Problem and spent hours to research it. The Server worked fine, but I was not able to install my app (Ios4 iPhone & ios5 iPad). I'm running it on nginx and tried to fix a/the?! misconfiguration.

But in my Case it was the missing "subtitle" in .plist. 

Now everything works fine!

**Comment by tanis2000** [comment]
RewriteBase isn't working for me as well.. it looks like the path of the plist file cannot be found.
Is there any news on this issue?

**Comment by radekskowron** [comment]
Maybe this will help somehow: https://github.com/TheRealKerni/HockeyKit/issues/113#issuecomment-5214761

**Comment by 0xced** [comment]
I solved the **Cannot connect to…** problem by replacing a space in the subdirectory containing the ipa and the plist with a hyphen.

**Comment by WesWedding** [comment]
Just chiming in to say that my own download problems went away once I got rid of spaces in filenames/directories, as well.  Worked fine if I visited with my Mac but an iOS device couldn't handle it.

Hopefully someone else stumbles on this thread and reads it all the way down like I did.
