### ISSUE TITLE
The HockeyKitlib xcodeproj could be more convient

### ISSUE THREAD

**Issue by sprhawk** [bitstadium/HockeyKit#97]
I moved some #import header from .h to .m,  then I can just include BWHockeyManager.h only,

my diffs

diff --git a/client/iOS/BWHockeyManager.h b/client/iOS/BWHockeyManager.h
index 4fd9ac7..e37b619 100644
--- a/client/iOS/BWHockeyManager.h
+++ b/client/iOS/BWHockeyManager.h
@@ -24,9 +24,9 @@

 #import <UIKit/UIKit.h>
-#import "BWGlobal.h"
-#import "BWApp.h"
-#import "BWHockeyViewController.h"
+
+@class BWApp;
+@class BWHockeyViewController;

 typedef enum {
    HockeyComparisonResultDifferent,
diff --git a/client/iOS/BWHockeyManager.m b/client/iOS/BWHockeyManager.m
index 85601c6..2f2ea54 100644
--- a/client/iOS/BWHockeyManager.m
+++ b/client/iOS/BWHockeyManager.m
@@ -27,6 +27,9 @@
 #import "UIImage+HockeyAdditions.h"
 #import <sys/sysctl.h>
 #import <Foundation/Foundation.h>
+#import "BWHockeyViewController.h"
+#import "BWApp.h"
+#import "BWGlobal.h"

 // API defines - do not change
 #define BETA_DOWNLOAD_TYPE_PROFILE @"profile"
diff --git a/client/iOS/BWHockeySettingsViewController.m b/client/iOS/BWHockeySettingsViewController.m
index 86619cb..4615b24 100644
--- a/client/iOS/BWHockeySettingsViewController.m
+++ b/client/iOS/BWHockeySettingsViewController.m
@@ -8,6 +8,7 @@

 #import "BWHockeySettingsViewController.h"
 #import "BWHockeyManager.h"
+#import "BWGlobal.h"

 #define BW_RGBCOLOR(r,g,b) [UIColor colorWithRed:(r)/255.0 green:(g)/255.0 blue:(b)/255.0 alpha:1]

**Comment by DerAndereAndi** [comment]
Hi there,

Moving internal headers to the .m is indeed good pratice. This would allow us to make only BWHockeyViewController and BWHockeyManager public in the library. So I changed that a bit, by only moving `BWApp.h` and `BWGlobal.h` out, since that is surely not required in the header.

Besides that, could you explain why this would allow you to only include BWHockeyManager? This should already be the case.

Thanks

**Comment by sprhawk** [comment]
Oh, I have realized that that BWHockeyViewController will use a delegate declaration that requires a PSStoreButton.h header. My project only needs BWHockeyManager, does not need an explicit declaration of BWHockeyViewController. 

However, you can just use some tricks to avoid the #import that delegate's header, for example , you can just #import the declaration of the protocol in the BWHockeyViewController.m, and in the PSStoreButton.m, you test with respondsToSelector and performSelector: methods. Either, you can just declare the protocol in BWHockeyViewController.h.

That will have the includes/lib simpler and cleaner.

I'm sorry, I can't understand the sentence in my pool English:"This should already be the case". 

Do you mean that original code could be only needed include only BWHockeyManager?

**Comment by DerAndereAndi** [comment]
Yes.

**Comment by sprhawk** [comment]
I'm failed to do that, so i refactored it....
